export default function ResultsPanel({ result }) {
  if (!result) return null;

  return (
    <section className="panel">
      <h2>Retrieved Chunks (top {result.retrieved_chunks.length})</h2>
      <div className="retrieved-grid">
        {result.retrieved_chunks.map((c) => (
          <div className="chunk-card ranked" key={`${c.source}-${c.chunk_index}`}>
            <div className="chunk-rank">#{c.rank}</div>
            <div className="chunk-meta">
              {c.source} · page {c.page_number} · chunk #{c.chunk_index}
            </div>
            <div className="chunk-score">similarity {c.similarity}</div>
            <div className="chunk-text">{c.text}</div>
          </div>
        ))}
      </div>

      <h2 className="answer-heading">Generated Answer</h2>
      <div className="answer-box">
        <div className="answer-text">{result.answer}</div>
        <div className="answer-footer">
          Generated by Groq ({result.llm_model}) from the {result.retrieved_chunks.length}{" "}
          chunks above · retrieval {result.timings_seconds.retrieval}s · generation{" "}
          {result.timings_seconds.generation}s
        </div>
      </div>
    </section>
  );
}
